project:
  type: website

website:
  title: "Stephanie C. Hicks, PhD"
  navbar:
    right:
      - href: projects.qmd
        text: Research themes
      - people.qmd
      - publications.qmd
      - href: software.qmd
        text: Software
      - href: teaching.qmd
        text: Teaching
      - talks.qmd
      - join.qmd
      - icon: github
        href: https://github.com/stephaniehicks
      - icon: twitter
        href: https://twitter.com/stephaniehicks
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

execute:
  freeze: auto

resources:
  - CNAME


